import google.generativeai as genai
from core.config import settings
import json
import re

# Configure Gemini
if settings.GEMINI_API_KEY:
    genai.configure(api_key=settings.GEMINI_API_KEY, transport='rest')

def generate_form_schema(description: str) -> dict:
    """
    Generates a JSON schema for a form based on the user's description using Gemini.
    """
    
    # Mock Mode: Fallback if no key is provided
    if not settings.GEMINI_API_KEY or len(settings.GEMINI_API_KEY) < 10:
        print("WARN: No valid Gemini Key found. Returning Mock Data.")
        return {
            "title": "Mock Application Form (Demo Mode)",
            "description": "This is a generated example because no Gemini API Key was found.",
            "fields": [
                {"id": "name", "label": "Full Name", "type": "text", "required": True},
                {"id": "email", "label": "Email Address", "type": "email", "required": True},
                {"id": "experience", "label": "Years of Experience", "type": "select", "options": ["0-1", "2-5", "5+"], "required": True},
                {"id": "bio", "label": "Short Bio", "type": "textarea", "required": False},
                {"id": "ai_model", "label": "Generated By", "type": "text", "placeholder": "Gemini Flash Mock", "required": False}
            ]
        }

    prompt = f"""
    You are an expert interactive form builder. 
    Task: Convert the user's description into a strict JSON schema for a web form.
    
    User Description: "{description}"
    
    Output Constraint: Return ONLY raw JSON. No markdown formatting (no ```json blocks).
    
    JSON Structure:
    {{
      "title": "Form Title",
      "description": "Short form description",
      "fields": [
        {{
          "id": "unique_id",
          "label": "Human readable label",
          "type": "text | email | number | textarea | select | checkbox",
          "required": true,
          "options": ["Option 1"] // Only for 'select' type
        }}
      ]
    }}
    """
    
    try:
        model = genai.GenerativeModel('gemini-flash-latest')
        response = model.generate_content(prompt)
        content = response.text
        
        # Clean up common markdown if Gemini adds it
        content = content.replace("```json", "").replace("```", "").strip()
        
        return json.loads(content)
    except Exception as e:
        error_msg = str(e)
        if "429" in error_msg:
            print(f"Rate Limit Hit: {e}")
            return {
                "error": "Rate Limit Exceeded",
                "details": "You are generating too fast for the Free Tier. Please wait 1 minute and try again.",
                # Return strict JSON structure even on error so frontend rendering doesn't break completely
                "title": "Rate Limit Exceeded", 
                "description": "Google Gemini Free Tier limit reached. Please wait ~60s.",
                "fields": []
            }
        
        print(f"Error generating form with Gemini: {e}")
        return {
             "title": "Error Fallback Form",
             "description": f"Could not connect to Gemini ({error_msg}).",
             "fields": [
                {"id": "error_trace", "label": "Error Trace", "type": "text", "required": False}
             ]
        }
